### ISSUE TITLE
Default sampling rates when using `StreamRecording` don't match

### ISSUE THREAD

**Issue by microbit-carlos** [lancaster-university/codal-microbit-v2#311] opened 2023-05-04 12:01 UTC
With this example, pressing down button A records sound and plays it back as soon as the button is released.
In this case, if the sampling rate is not set in `uBit.audio.mixer.addChannel()` the playback is speeded up.

```cpp
#include "MicroBit.h"
#include "StreamRecording.h"

MicroBit uBit;

static void onButtonPress(MicroBitEvent) {
    static SplitterChannel *splitterChannel = uBit.audio.splitter->createChannel();
    static StreamRecording *recording = new StreamRecording(*splitterChannel);

    // The defaults here don't match
    static MixerChannel *channel = uBit.audio.mixer.addChannel(*recording);
    // This version works
    // static MixerChannel *channel = uBit.audio.mixer.addChannel(*recording, 11000);

    uBit.audio.processor->setGain(0.08);
    channel->setVolume(100);
    uBit.audio.mixer.setVolume(1023);
    MicroBitAudio::requestActivation();

    recording->record();
    while (uBit.buttonA.isPressed()) {
        uBit.sleep(5);
    }
    recording->stop();
    uBit.audio.mic->disable();
    uBit.audio.deactivateMic();

    recording->play();
    while (recording->isPlaying()) {
        uBit.sleep(20);
    }
    recording->erase();
}

int main() {
    uBit.init();

    uBit.messageBus.listen(MICROBIT_ID_BUTTON_A, MICROBIT_BUTTON_EVT_DOWN, onButtonPress);

    while (true) {
        uBit.sleep(1000);
    }
}
```

**Comment by microbit-carlos** [comment] 2023-05-18 14:06
@JohnVidler I've tested this with the latest CODAL and still sounds speed up if no sampling rate is specified in the user code.

**Comment by microbit-carlos** [comment] 2023-06-29 14:17
I can confirm this is still replicable with CODAL v0.2.55.

Updated, smaller example to replicate:
[MICROBIT.hex.zip](https://github.com/lancaster-university/codal-microbit-v2/files/11906682/MICROBIT.hex.zip)

```cpp
#include "MicroBit.h"
#include "StreamRecording.h"

MicroBit uBit;

static void onButtonPress(MicroBitEvent) {
    static SplitterChannel *splitterChannel = uBit.audio.splitter->createChannel();
    static StreamRecording *recording = new StreamRecording(*splitterChannel);

    // The defaults here don't match
    static MixerChannel *channel = uBit.audio.mixer.addChannel(*recording);
    // This version works
    //static MixerChannel *channel = uBit.audio.mixer.addChannel(*recording, 11000);

    channel->setVolume(100);
    MicroBitAudio::requestActivation();

    recording->recordAsync();
    while (uBit.buttonA.isPressed()) {
        uBit.sleep(5);
    }
    recording->stop();

    recording->play();
    while (recording->isPlaying()) {
        uBit.sleep(20);
    }
    recording->erase();
}

int main() {
    uBit.init();

    uBit.messageBus.listen(MICROBIT_ID_BUTTON_A, MICROBIT_BUTTON_EVT_DOWN, onButtonPress);

    while (true) {
        uBit.sleep(1000);
    }
}
```

**Comment by microbit-carlos** [comment] 2023-07-11 12:34
I've checked again, ensuring I'm using the latest commits from all dependencies, I can still replicate this issue.

**Comment by JohnVidler** [comment] 2023-11-13 12:43
So _technically_ this is intended behaviour, as the `addChannel` method defaulted to setting the sample rate to zero, which caused the mixer channel to use the mixer sample rate (44k) which is far higher than the default mic sample rate (11k), and I agree that this is weird default behaviour here.

I've added a new `CONFIG_MIXER_DEFAULT_CHANNEL_SAMPLERATE` constant that sets _both_ the mic default rate and the new mixer channel rate to 11k (both of which can be configured by the user at call-time, so anyone who cares to set a value will see no change here).

I'm not thrilled by that config name, but it aligns with others we have in the mixer, but I'm open to creating a distinct `CONFIG_MIC_DEFAULT_SAMPLE_SAMPLERATE` which defaults to whatever the `CONFIG_MIXER_DEFAULT_CHANNEL_SAMPLERATE` is, so these align by default, but can be set independently, but honestly as these can be set by the user at runtime anyway, this only matters in the one case where no preference at either end is expressed, so having just the one is fine, barring any specific requests for two.

See this commit for the patch; https://github.com/lancaster-university/codal-microbit-v2/commit/d54ce9b784ef1bba22c075b281bb877abf53ea18 and I'm marking this as 'complete' for now, but feel free to reopen if major changes are needed (like the addition of the extra mic-specific config var)

**Closed by JohnVidler** 2023-11-13 12:43 UTC
Labels: p0
