### ISSUE TITLE
PacketBuffer API in Docs is actually ManagedString's API

### ISSUE THREAD

**Issue by tapanther** [lancaster-university/codal-microbit-v2#88] opened 2021-03-13 07:31 UTC
In the online documentation, `PacketBuffer`'s [API section](https://lancaster-university.github.io/microbit-docs/data-types/packetbuffer/#api) is actually `ManagedString`'s API.

**Comment by JohnVidler** [comment] 2022-05-05 15:07
Duplicate of https://github.com/lancaster-university/microbit-docs/issues/82 closing here

**Closed by JohnVidler** 2022-05-05 15:07 UTC
Labels: documentation
