### ISSUE TITLE
display readLightLevel always returns 0

### ISSUE THREAD

**Issue by microbit-carlos** [lancaster-university/codal-microbit-v2#14] opened 2020-11-05 14:26 UTC
This example programme always reads 0:

```cpp
#include "MicroBit.h"

MicroBit uBit;

int main() {
    while (1) {
        uBit.serial.send(ManagedString(uBit.display.readLightLevel()) + "\r\n");
        uBit.sleep(250);
    }
}
```

**Comment by finneyj** [comment] 2020-11-05 16:04
thanks @microbit-carlos. This certainly used to work - must be a regression... I'll take a look.

**Comment by microbit-mark** [comment] 2020-11-06 13:04
Seems to be different behaviour on v1 and v2 for light level. On v2 the initial reading is 0 and on v1 still 255 as documented in 
https://github.com/lancaster-university/microbit-dal/issues/426

**Comment by finneyj** [comment] 2020-11-07 17:54
Fixed in master for v2.

@microbit-mark - I think we fixed that bug on v1? I seem to remember a contribution for that...

**Comment by microbit-carlos** [comment] 2020-11-09 17:27
Just to clarify, the issue wasn't about the first value, as in my example programme the value returned by `uBit.display.readLightLevel()` was **always** `0`.

**Comment by finneyj** [comment] 2020-11-09 17:31
It takes a fair bit of light to trip it...

**Comment by finneyj** [comment] 2020-11-09 17:32
as did a v1....

**Comment by microbit-carlos** [comment] 2020-11-09 17:33
When I was testing this last week I had my phone flash on top of the display and it was reading zeros.
Trying to rebuild now, but getting nothing on the serial.

**Comment by finneyj** [comment] 2020-11-09 17:35
Phone flash should definitely do it! it tested through fine on my build though.

I did rebuild your test though, maybe there's something else I missed...

**Comment by finneyj** [comment] 2020-11-09 17:36
uBit.init() ???

**Comment by finneyj** [comment] 2020-11-09 17:40
Above test works against master both with and without uBit.init() for me @microbit-carlos. 

Puzzling!

**Comment by microbit-carlos** [comment] 2020-11-09 17:42
The serial issue was a problem with my current setup (had tested something different before and left DAPLink in a bad state), so that's no problem.

I was able to test a rebuilt with the latest master in all the libraries and now works!
If the only change was the initial value I'm not sure why it wasn't working before, but we can consider this fixed 👍

**Comment by finneyj** [comment] 2020-11-09 17:45
hurrah!

Thanks @microbit-carlos,

**Closed by finneyj** 2020-11-09 17:45 UTC

**Comment by microbit-carlos** [comment] 2020-11-09 17:48
> Seems to be different behaviour on v1 and v2 for light level. On v2 the initial reading is 0 and on v1 still 255 as documented in
> [lancaster-university/microbit-dal#426](https://github.com/lancaster-university/microbit-dal/issues/426)

@microbit-mark have you tested this recently? If this is still the case we should open a new issue here.

A related issue I remember was found with the Scratch plugin, but I think ultimately the solution was to have an event to indicate when the light readings are ready? As the averaging wasn't good until enough readings were collected.

If the initial values are different in v1 and v2 we might want to look into that.

**Comment by martinwork** [comment] 2020-11-09 19:42
I have tested light level recently - both MakeCode and CPP. I get good readings from v1 and v2. v2 CODAL has a pause now, so doesn't deliver a bad first value. v1 DAL still starts at 255.

**Comment by microbit-mark** [comment] 2020-11-10 08:09
Thanks @martinwork. It appears this is fixed for codal, but still present in DAL as per lancaster-university/microbit-dal#426
@finneyj I don't think it was fixed in the DAL as it's still reproducing for David in MakeCode https://github.com/microsoft/pxt-microbit/issues/3451

**Comment by microbit-carlos** [comment] 2020-11-10 10:10
@finneyj if the original fix for this in the v1 DAL was to create an event to indicate when the readings are ready, do we have the same event in CODAL?

Was there a reason not to implement a fix like this one in v1 DAL? https://github.com/lancaster-university/codal-microbit-v2/commit/77693b2b283b7e456371c012f4c81b7017b1a58d#diff-64163a3b89cf79ee79d60156c44f4e855136b12a4130d6fdd7251c50b9bd0927R336

**Comment by mod7ex** [comment] 2026-02-05 22:21
i still get same problem 0 reading for v2

**Comment by martinwork** [comment] 2026-02-05 22:32
Hi @mod7ex With this example, I see about 150 under my desk lamp, but it's really easy to get zero if I shade the micro:bit.
https://makecode.microbit.org/_EDJMYYa7ffEd

Can you post an example?

**Comment by mod7ex** [comment] 2026-02-07 09:01
Hi @martinwork thanks
this is the example https://makecode.microbit.org/_PvpVe54mt4hc it always shows 0 in complete dark or in sun light 
only when i cover the upper 5 LEDs it shows larger than 0

**Comment by martinwork** [comment] 2026-02-07 14:13
@mod7ex Your project seemed to give good values from the start for me.

But with the pause moved after the sensor read, the first value after reset is always 0:
https://makecode.microbit.org/_P716VD6TiJK1

This project also has first reading zero: https://makecode.microbit.org/_6uXFp2cE2D7L
It still happens with the nezha extension removed: https://makecode.microbit.org/_dtoPcKbf0Dag
But it's OK with the PlanetX extension removed: https://makecode.microbit.org/_ffA72fcwgPRv

So the problem appears to be something PlanetX is doing, even though no blocks are used in the project.  If you agree, I think it would be appropriate to create an issue in https://github.com/elecfreaks/pxt-PlanetX/issues

For now, either remove PlanetX, or insert a pause before the first light level read.
https://makecode.microbit.org/extensions#:~:text=Removing%20an%20extension%20from%20a%20project
https://makecode.microbit.org/_72WcPg4FwRsF
https://makecode.microbit.org/_dK7am8UvDCTq
